### ISSUE TITLE
Tapping last item in list doesn't bring to top.

### ISSUE THREAD

**Issue by QoLTech** [quire-io/scroll-to-index#1] opened 2019-04-29 18:27 UTC
In the example, there is a counter that tracks if the counter is greater than the number of items in the list and if so, it sets the counter to 0 and attempts to scroll to the 0th index. However, when I'm implementing this, it tries to keep scrolling to the bottom. Am I missing something?

**Comment by jerrywell** [comment] 2019-04-30 03:35
can you reproduce it inside the example? if so, please post the code here. you can also print the value for your call to `scrollToIndex` to see if it's inside your given index value for `AutoScrollTag`

**Comment by ellis-wang** [comment] 2019-05-29 08:22
i want to scroll to a certain item without animation, what should i do?

**Comment by jerrywell** [comment] 2019-05-29 09:21
@ellis-wang 
unfortunately, this package didn't have this options. Since flutter's scroll controller only provide the `Future<void> animateTo(double offset)` and `void jumpTo(double value)`. if we need to move to a index without animation, the jumpTo() is the only one way to do that. but searching for index comes on the render object to track which offset we need to move. so there must be a signal(that is, a future, which is not provided by jumpTo()) to notify the rendering is done. We can then search for the indexed object and move again. however, you can try to use `Duration(microsecond: 1)` as the duration parameter of scrollToIndex() to reduce the animation duration as much as you can.

**Comment by ellis-wang** [comment] 2019-05-29 09:53
> @ellis-wang
> unfortunately, this package didn't have this options. Since flutter's scroll controller only provide the `Future<void> animateTo(double offset)` and `void jumpTo(double value)`. if we need to move to a index without animation, the jumpTo() is the only one way to do that. but searching for index comes on the render object to track which offset we need to move. so there must be a signal(that is, a future, which is not provided by jumpTo()) to notify the rendering is done. We can then search for the indexed object and move again. however, you can try to use `Duration(microsecond: 1)` as the duration parameter of scrollToIndex() to reduce the animation duration as much as you can.

ok,thx a lot :)

**Comment by jerrywell** [comment] 2019-06-17 02:15
I'm closing this issue since we don't have enough information to locate where the bug is.

**Closed by jerrywell** 2019-06-17 02:15 UTC
